AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.14

  Sample SAM Template for lambda-python3.14

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  ProgramTableName:
    Type: String
    Default: programs
    Description: "Nombre de la tabla DynamoDB usada por el lambda program"
  ImagesTableName:
    Type: String
    Default: images
    Description: "Nombre de la tabla DynamoDB usada por el lambda images"
<<<<<<< HEAD
  HeroTableName:
    Type: String
    Default: hero
    Description: "Nombre de la tabla DynamoDB usada por el lambda hero"
=======
  VideosTableName:
    Type: String
    Default: videos
    Description: "Nombre de la tabla DynamoDB usada por el lambda videos"
>>>>>>> aad4b624f80b0bf7af2ed4bc44dbe63a4ba0c417

Resources:
  AuthValidateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Events:
        AuthValidateUser:
          Type: Api
          Properties:
            Path: /auth/validate
            Method: post

  ProgramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: program/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          PROGRAM_TABLE_NAME: !Ref ProgramTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProgramTableName
      Events:
        ProgramGetById:
          Type: Api
          Properties:
            Path: /program/{program_id}
            Method: get

  ImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: images/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          IMAGES_TABLE_NAME: !Ref ImagesTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTableName
      Events:
        ImagesList:
          Type: Api
          Properties:
            Path: /images
            Method: get
        ImagesCreate:
          Type: Api
          Properties:
            Path: /images
            Method: post
        ImagesGetById:
          Type: Api
          Properties:
            Path: /images/{image_id}
            Method: get
        ImagesUpdate:
          Type: Api
          Properties:
            Path: /images/{image_id}
            Method: put

<<<<<<< HEAD
  HeroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hero/
=======
  VideosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: videos/
>>>>>>> aad4b624f80b0bf7af2ed4bc44dbe63a4ba0c417
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
<<<<<<< HEAD
          HERO_TABLE_NAME: !Ref HeroTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HeroTableName
      Events:
        HeroList:
          Type: Api
          Properties:
            Path: /hero
            Method: get
        HeroCreate:
          Type: Api
          Properties:
            Path: /hero
            Method: post
        HeroGetById:
          Type: Api
          Properties:
            Path: /hero/{hero_id}
            Method: get
        HeroUpdate:
          Type: Api
          Properties:
            Path: /hero/{hero_id}
=======
          VIDEOS_TABLE_NAME: !Ref VideosTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VideosTableName
      Events:
        VideosList:
          Type: Api
          Properties:
            Path: /videos
            Method: get
        VideosCreate:
          Type: Api
          Properties:
            Path: /videos
            Method: post
        VideosGetById:
          Type: Api
          Properties:
            Path: /videos/{video_id}
            Method: get
        VideosUpdate:
          Type: Api
          Properties:
            Path: /videos/{video_id}
>>>>>>> aad4b624f80b0bf7af2ed4bc44dbe63a4ba0c417
            Method: put

Outputs:
  AuthValidateUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Auth validation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/auth/validate/"
  AuthValidateUserFunction:
    Description: "Auth validation Lambda Function ARN"
    Value: !GetAtt AuthValidateUserFunction.Arn
  AuthValidateUserFunctionIamRole:
    Description: "Implicit IAM Role created for Auth validation function"
    Value: !GetAtt AuthValidateUserFunctionRole.Arn
  ProgramApi:
    Description: "API Gateway endpoint URL for Prod stage for Program function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/program/{program_id}/"
  ProgramFunction:
    Description: "Program Lambda Function ARN"
    Value: !GetAtt ProgramFunction.Arn
  ProgramFunctionIamRole:
    Description: "Implicit IAM Role created for Program function"
    Value: !GetAtt ProgramFunctionRole.Arn
  ImagesApi:
    Description: "API Gateway endpoint URL for Prod stage for Images function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/images"
  ImagesFunction:
    Description: "Images Lambda Function ARN"
    Value: !GetAtt ImagesFunction.Arn
  ImagesFunctionIamRole:
    Description: "Implicit IAM Role created for Images function"
    Value: !GetAtt ImagesFunctionRole.Arn
<<<<<<< HEAD
  HeroApi:
    Description: "API Gateway endpoint URL for Prod stage for Hero function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hero/"
  HeroFunction:
    Description: "Hero Lambda Function ARN"
    Value: !GetAtt HeroFunction.Arn
  HeroFunctionIamRole:
    Description: "Implicit IAM Role created for Hero function"
    Value: !GetAtt HeroFunctionRole.Arn
=======
  VideosApi:
    Description: "API Gateway endpoint URL for Prod stage for Videos function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/videos"
  VideosFunction:
    Description: "Videos Lambda Function ARN"
    Value: !GetAtt VideosFunction.Arn
  VideosFunctionIamRole:
    Description: "Implicit IAM Role created for Videos function"
    Value: !GetAtt VideosFunctionRole.Arn
>>>>>>> aad4b624f80b0bf7af2ed4bc44dbe63a4ba0c417
