AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.14

  Sample SAM Template for lambda-python3.14

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  ProgramTableName:
    Type: String
    Default: programs
    Description: "Nombre de la tabla DynamoDB usada por el lambda program"
  CategoryTableName:
    Type: String
    Default: categorys
    Description: "Nombre de la tabla DynamoDB usada por el lambda category"
  ImagesTableName:
    Type: String
    Default: images
    Description: "Nombre de la tabla DynamoDB usada por el lambda images"
  HeroTableName:
    Type: String
    Default: heros
    Description: "Nombre de la tabla DynamoDB usada por el lambda hero"
  VideosTableName:
    Type: String
    Default: videos
    Description: "Nombre de la tabla DynamoDB usada por el lambda videos"
  DestinationTableName:
    Type: String
    Default: destinations
    Description: "Nombre de la tabla DynamoDB usada por el lambda destination"

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'https://new.ifxsoccer.com'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,POST,PUT,OPTIONS'"

  ApiGatewayDefault4xxResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ServerlessRestApi
      ResponseType: DEFAULT_4XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://new.ifxsoccer.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,OPTIONS'"

  ApiGatewayDefault5xxResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ServerlessRestApi
      ResponseType: DEFAULT_5XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://new.ifxsoccer.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,OPTIONS'"

  AuthValidateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Events:
        AuthValidateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /auth/validate
            Method: post

  ProgramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: program/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          PROGRAM_TABLE_NAME: !Ref ProgramTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProgramTableName
      Events:
        ProgramList:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /program
            Method: get
        ProgramCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /program
            Method: post
        ProgramGetById:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /program/{program_id}
            Method: get
        ProgramUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /program/{program_id}
            Method: put

  CategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: category/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          CATEGORY_TABLE_NAME: !Ref CategoryTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoryTableName
      Events:
        CategoryList:
          Type: Api
          Properties:
            Path: /category
            Method: get
        CategoryCreate:
          Type: Api
          Properties:
            Path: /category
            Method: post
        CategoryGetById:
          Type: Api
          Properties:
            Path: /category/{category_id}
            Method: get
        CategoryUpdate:
          Type: Api
          Properties:
            Path: /category/{category_id}
            Method: put

  ImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: images/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          IMAGES_TABLE_NAME: !Ref ImagesTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTableName
      Events:
        ImagesList:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /images
            Method: get
        ImagesCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /images
            Method: post
        ImagesGetById:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /images/{image_id}
            Method: get
        ImagesUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /images/{image_id}
            Method: put

  HeroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hero/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          HERO_TABLE_NAME: !Ref HeroTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HeroTableName
      Events:
        HeroList:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /hero
            Method: get
        HeroCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /hero
            Method: post
        HeroGetById:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /hero/{hero_id}
            Method: get
        HeroUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /hero/{hero_id}
            Method: put
        HeroListPlural:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /heros
            Method: get
        HeroCreatePlural:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /heros
            Method: post
        HeroGetByIdPlural:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /heros/{hero_id}
            Method: get
        HeroUpdatePlural:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /heros/{hero_id}
            Method: put

  VideosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: videos/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          VIDEOS_TABLE_NAME: !Ref VideosTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VideosTableName
      Events:
        VideosList:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /videos
            Method: get
        VideosCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /videos
            Method: post
        VideosGetById:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /videos/{video_id}
            Method: get
        VideosUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /videos/{video_id}
            Method: put

  DestinationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: destination/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          DESTINATION_TABLE_NAME: !Ref DestinationTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DestinationTableName
      Events:
        DestinationList:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /destination
            Method: get
        DestinationCreate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /destination
            Method: post
        DestinationGetById:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /destination/{destination_id}
            Method: get
        DestinationUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /destination/{destination_id}
            Method: put

Outputs:
  AuthValidateUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Auth validation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/auth/validate/"
  AuthValidateUserFunction:
    Description: "Auth validation Lambda Function ARN"
    Value: !GetAtt AuthValidateUserFunction.Arn
  AuthValidateUserFunctionIamRole:
    Description: "Implicit IAM Role created for Auth validation function"
    Value: !GetAtt AuthValidateUserFunctionRole.Arn
  ProgramApi:
    Description: "API Gateway endpoint URL for Prod stage for Program function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/program/"
  ProgramFunction:
    Description: "Program Lambda Function ARN"
    Value: !GetAtt ProgramFunction.Arn
  ProgramFunctionIamRole:
    Description: "Implicit IAM Role created for Program function"
    Value: !GetAtt ProgramFunctionRole.Arn
  CategoryApi:
    Description: "API Gateway endpoint URL for Prod stage for Category function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/category/"
  CategoryFunction:
    Description: "Category Lambda Function ARN"
    Value: !GetAtt CategoryFunction.Arn
  CategoryFunctionIamRole:
    Description: "Implicit IAM Role created for Category function"
    Value: !GetAtt CategoryFunctionRole.Arn
  ImagesApi:
    Description: "API Gateway endpoint URL for Prod stage for Images function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/images"
  ImagesFunction:
    Description: "Images Lambda Function ARN"
    Value: !GetAtt ImagesFunction.Arn
  ImagesFunctionIamRole:
    Description: "Implicit IAM Role created for Images function"
    Value: !GetAtt ImagesFunctionRole.Arn
  HeroApi:
    Description: "API Gateway endpoint URL for Prod stage for Hero function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hero/"
  HeroFunction:
    Description: "Hero Lambda Function ARN"
    Value: !GetAtt HeroFunction.Arn
  HeroFunctionIamRole:
    Description: "Implicit IAM Role created for Hero function"
    Value: !GetAtt HeroFunctionRole.Arn
  VideosApi:
    Description: "API Gateway endpoint URL for Prod stage for Videos function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/videos"
  VideosFunction:
    Description: "Videos Lambda Function ARN"
    Value: !GetAtt VideosFunction.Arn
  VideosFunctionIamRole:
    Description: "Implicit IAM Role created for Videos function"
    Value: !GetAtt VideosFunctionRole.Arn
  DestinationApi:
    Description: "API Gateway endpoint URL for Prod stage for Destination function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/destination"
  DestinationFunction:
    Description: "Destination Lambda Function ARN"
    Value: !GetAtt DestinationFunction.Arn
  DestinationFunctionIamRole:
    Description: "Implicit IAM Role created for Destination function"
    Value: !GetAtt DestinationFunctionRole.Arn
